"use client";
import { useMemo, useState } from "react";
import { useTradingStore } from "@/lib/trading/store";
import { computeRollingCorrelation, detectCorrelationBreakdowns, computeLiveCorrelationMatrix, computeAllLeadLags, classifyRiskRegime, DEFAULT_PAIRS, MONITOR_SYMBOLS } from "@/lib/trading/correlation-arb";
import { fmtTime } from "@/lib/trading/format";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Line, LineChart, CartesianGrid, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { cn } from "@/lib/utils";
import { Activity, ArrowRight, Grid, Shield, TrendingUp, AlertTriangle } from "lucide-react";

type View = "breakdowns" | "matrix" | "leadlag" | "regime" | "chart";
const VIEWS: { id: View; name: string; icon: any }[] = [{ id: "breakdowns", name: "Breakdowns", icon: AlertTriangle }, { id: "matrix", name: "Matrix", icon: Grid }, { id: "leadlag", name: "Lead-Lag", icon: ArrowRight }, { id: "regime", name: "Risk Regime", icon: Shield }, { id: "chart", name: "Rolling Corr", icon: Activity }];

const SEV = { NORMAL: "bg-muted text-muted-foreground border-border", ELEVATED: "bg-amber-500/15 text-amber-400 border-amber-500/30", EXTREME: "bg-rose-500/15 text-rose-400 border-rose-500/30" };

export function CorrelationArbitrage() {
  const [view, setView] = useState<View>("breakdowns");
  const [pairA, setPairA] = useState("ES"); const [pairB, setPairB] = useState("NQ");
  const tickCount = useTradingStore(s => s.tickCount);
  const breakdowns = useMemo(() => detectCorrelationBreakdowns(DEFAULT_PAIRS, 50, 200), [tickCount]);
  const corrMatrix = useMemo(() => computeLiveCorrelationMatrix(MONITOR_SYMBOLS, 50), [tickCount]);
  const leadLags = useMemo(() => computeAllLeadLags(DEFAULT_PAIRS), [tickCount]);
  const regime = useMemo(() => classifyRiskRegime(), [tickCount]);
  const rollingCorr = useMemo(() => computeRollingCorrelation(pairA, pairB, 50, 200), [pairA, pairB, tickCount]);

  return (
    <div className="space-y-4">
      <div className="flex items-center gap-1 flex-wrap">{VIEWS.map(v => <button key={v.id} onClick={() => setView(v.id)} className={cn("flex items-center gap-1.5 px-3 py-1.5 rounded-md text-xs border transition-colors", view === v.id ? "bg-primary/15 text-primary border-primary/30" : "border-border text-muted-foreground hover:bg-muted/40")}><v.icon className="w-3.5 h-3.5" />{v.name}</button>)}</div>
      {view === "breakdowns" && (<div className="space-y-3"><div className="grid grid-cols-2 md:grid-cols-4 gap-2"><Card className="p-2.5"><div className="text-[9px] uppercase text-muted-foreground">Pairs</div><div className="text-sm font-mono font-semibold">{breakdowns.length}</div></Card><Card className="p-2.5 border-rose-500/20 bg-rose-500/5"><div className="text-[9px] uppercase text-muted-foreground">Extreme</div><div className="text-sm font-mono font-semibold text-rose-400">{breakdowns.filter(b => b.severity === "EXTREME").length}</div></Card><Card className="p-2.5 border-amber-500/20 bg-amber-500/5"><div className="text-[9px] uppercase text-muted-foreground">Elevated</div><div className="text-sm font-mono font-semibold text-amber-400">{breakdowns.filter(b => b.severity === "ELEVATED").length}</div></Card><Card className="p-2.5"><div className="text-[9px] uppercase text-muted-foreground">Breakdowns</div><div className="text-sm font-mono font-semibold text-rose-400">{breakdowns.filter(b => b.signal === "BREAKDOWN").length}</div></Card></div>
        <div className="space-y-2">{breakdowns.map((b, i) => <Card key={i} className={cn("border", b.severity === "EXTREME" ? "border-rose-500/30 bg-rose-500/5" : b.severity === "ELEVATED" ? "border-amber-500/30 bg-amber-500/5" : "border-border")}><CardContent className="p-3"><div className="flex items-start justify-between gap-3"><div className="flex-1"><div className="flex items-center gap-2 mb-1"><span className="text-xs font-mono font-semibold">{b.pair}</span><Badge variant="outline" className={cn("text-[9px]", SEV[b.severity])}>{b.severity}</Badge><span className={cn("text-[10px] font-medium", b.signal === "BREAKDOWN" ? "text-rose-400" : b.signal === "STRENGTHENING" ? "text-emerald-400" : "text-muted-foreground")}>{b.signal}</span></div><p className="text-[11px] text-muted-foreground">{b.description}</p><div className="flex items-center gap-3 mt-1.5 text-[10px] font-mono"><span>Current: <span className={cn("font-semibold", b.currentCorr >= 0 ? "text-emerald-400" : "text-rose-400")}>{b.currentCorr.toFixed(3)}</span></span><span>Hist: <span className="text-foreground">{b.historicalMean.toFixed(3)}</span></span><span>Z: <span className={cn("font-semibold", Math.abs(b.zScore) > 2 ? "text-rose-400" : Math.abs(b.zScore) > 1 ? "text-amber-400" : "text-muted-foreground")}>{b.zScore.toFixed(2)}</span></span></div></div><Button variant="outline" size="sm" className="h-7 text-xs shrink-0" onClick={() => { setPairA(b.symbolA); setPairB(b.symbolB); setView("chart"); }}>Chart</Button></div></CardContent></Card>)}</div></div>)}
      {view === "matrix" && (<Card><CardHeader className="py-2"><CardTitle className="text-xs">Live Correlation Matrix (50-bar)</CardTitle></CardHeader><CardContent><div className="overflow-x-auto"><table className="text-[10px] font-mono"><thead><tr><th className="p-1"></th>{corrMatrix.symbols.map(s => <th key={s} className="p-1 text-muted-foreground text-[9px]">{s}</th>)}</tr></thead><tbody>{corrMatrix.matrix.map((row, i) => <tr key={i}><td className="p-1 text-muted-foreground text-[9px] pr-2">{corrMatrix.symbols[i]}</td>{row.map((v, j) => <td key={j} className={cn("p-1.5 text-center tabular-nums border border-border/30 cursor-pointer", v > 0.7 && "bg-emerald-500/30 text-emerald-300", v > 0.3 && v <= 0.7 && "bg-emerald-500/15 text-emerald-400", v < -0.3 && v >= -0.7 && "bg-rose-500/15 text-rose-400", v < -0.7 && "bg-rose-500/30 text-rose-300", Math.abs(v) <= 0.3 && i !== j && "text-muted-foreground", i === j && "bg-primary/20")} onClick={() => { if (i !== j) { setPairA(corrMatrix.symbols[i]); setPairB(corrMatrix.symbols[j]); setView("chart"); } }} title={`${corrMatrix.symbols[i]} vs ${corrMatrix.symbols[j]}`}>{v.toFixed(2)}</td>)}</tr>)}</tbody></table></div><div className="text-[10px] text-muted-foreground mt-2">Green = positive, Red = negative. Click cell to view chart.</div></CardContent></Card>)}
      {view === "leadlag" && (<Card><CardHeader className="py-2"><CardTitle className="text-xs flex items-center gap-2"><ArrowRight className="w-3.5 h-3.5" /> Lead-Lag Analysis</CardTitle></CardHeader><CardContent className="p-0"><table className="w-full text-xs"><thead className="bg-muted/40 border-y border-border"><tr className="text-muted-foreground text-[10px] uppercase"><th className="text-left py-2 px-3">Pair</th><th className="text-center py-2 px-3">Leader</th><th className="text-center py-2 px-3">→</th><th className="text-center py-2 px-3">Lagger</th><th className="text-right py-2 px-3">Lag</th><th className="text-right py-2 px-3">Corr</th><th className="text-right py-2 px-3">Sig</th></tr></thead><tbody>{leadLags.map((ll, i) => <tr key={i} className="border-b border-border/40 hover:bg-muted/30"><td className="py-2 px-3 font-mono font-medium">{ll.pair}</td><td className="py-2 px-3 text-center"><Badge variant="outline" className="text-[9px] bg-emerald-500/15 text-emerald-400">{ll.leader}</Badge></td><td className="py-2 px-3 text-center text-muted-foreground">→</td><td className="py-2 px-3 text-center"><Badge variant="outline" className="text-[9px] bg-amber-500/15 text-amber-400">{ll.lagger}</Badge></td><td className="py-2 px-3 text-right font-mono">{ll.lagBars}</td><td className={cn("py-2 px-3 text-right font-mono", ll.correlation > 0.3 ? "text-emerald-400" : "text-muted-foreground")}>{ll.correlation.toFixed(3)}</td><td className="py-2 px-3 text-right"><div className="flex items-center justify-end gap-1.5"><div className="w-12 h-1.5 bg-muted rounded-full overflow-hidden"><div className={cn("h-full", ll.significance > 0.5 ? "bg-emerald-500" : ll.significance > 0.25 ? "bg-amber-500" : "bg-muted-foreground")} style={{ width: `${ll.significance * 100}%` }} /></div><span className="font-mono text-[10px] w-8">{(ll.significance * 100).toFixed(0)}%</span></div></td></tr>)}</tbody></table></CardContent></Card>)}
      {view === "regime" && (<div className="space-y-3"><Card className={cn("border", regime.regime === "RISK_ON" ? "border-emerald-500/30 bg-emerald-500/5" : regime.regime === "RISK_OFF" ? "border-rose-500/30 bg-rose-500/5" : "border-border")}><CardContent className="p-4"><div className="flex items-center gap-4">{regime.regime === "RISK_ON" ? <TrendingUp className="w-8 h-8 text-emerald-400" /> : regime.regime === "RISK_OFF" ? <Shield className="w-8 h-8 text-rose-400" /> : <Activity className="w-8 h-8 text-muted-foreground" />}<div><div className="text-lg font-semibold">{regime.regime.replace("_", " ")}</div><div className="text-xs text-muted-foreground">{regime.description}</div></div><div className="ml-auto text-right"><div className="text-[10px] text-muted-foreground">Confidence</div><div className="text-2xl font-mono font-bold">{(regime.confidence * 100).toFixed(0)}%</div></div></div></CardContent></Card><div className="grid grid-cols-1 md:grid-cols-3 gap-2">{regime.indicators.map((ind: any, i: number) => <Card key={i} className={cn("p-2.5 border", ind.signal === "RISK_ON" ? "border-emerald-500/20 bg-emerald-500/5" : ind.signal === "RISK_OFF" ? "border-rose-500/20 bg-rose-500/5" : "border-border")}><div className="text-[10px] uppercase text-muted-foreground">{ind.name}</div><div className={cn("text-sm font-mono font-semibold mt-0.5", ind.signal === "RISK_ON" ? "text-emerald-400" : ind.signal === "RISK_OFF" ? "text-rose-400" : "")}>{ind.value >= 0 ? "+" : ""}{ind.value.toFixed(2)}%</div><Badge variant="outline" className={cn("text-[9px] mt-1", ind.signal === "RISK_ON" ? "bg-emerald-500/15 text-emerald-400" : ind.signal === "RISK_OFF" ? "bg-rose-500/15 text-rose-400" : "bg-muted text-muted-foreground")}>{ind.signal.replace("_", " ")}</Badge></Card>)}</div></div>)}
      {view === "chart" && (<div className="space-y-3"><Card><CardContent className="p-3 flex items-center gap-3"><select value={pairA} onChange={e => setPairA(e.target.value)} className="bg-muted/50 border border-border rounded px-2 py-1.5 text-xs font-mono">{MONITOR_SYMBOLS.map(s => <option key={s} value={s}>{s}</option>)}</select><span className="text-muted-foreground text-xs">vs</span><select value={pairB} onChange={e => setPairB(e.target.value)} className="bg-muted/50 border border-border rounded px-2 py-1.5 text-xs font-mono">{MONITOR_SYMBOLS.map(s => <option key={s} value={s}>{s}</option>)}</select>{rollingCorr.length > 0 && <div className="flex items-center gap-4 text-xs ml-auto"><span>Current: <span className="font-mono font-semibold">{rollingCorr[rollingCorr.length-1].corr.toFixed(3)}</span></span><span>Z: <span className={cn("font-mono font-semibold", Math.abs(rollingCorr[rollingCorr.length-1].zScore) > 2 ? "text-rose-400" : Math.abs(rollingCorr[rollingCorr.length-1].zScore) > 1 ? "text-amber-400" : "text-muted-foreground")}>{rollingCorr[rollingCorr.length-1].zScore.toFixed(2)}</span></span></div>}</CardContent></Card>
        <Card><CardHeader className="py-2"><CardTitle className="text-xs">{pairA}/{pairB} — Rolling 50-bar Correlation</CardTitle></CardHeader><CardContent><div className="h-[300px]"><ResponsiveContainer width="100%" height="100%"><LineChart data={rollingCorr.map(r => ({ time: fmtTime(r.time), corr: r.corr, zScore: r.zScore }))}><CartesianGrid strokeDasharray="3 3" stroke="hsl(var(--border))" opacity={0.2} /><XAxis dataKey="time" tick={{ fontSize: 9, fill: "hsl(var(--muted-foreground))" }} interval={Math.max(1, Math.floor(rollingCorr.length / 8))} /><YAxis domain={[-1,1]} tick={{ fontSize: 10, fill: "hsl(var(--muted-foreground))" }} width={40} orientation="right" /><Tooltip formatter={(v: any) => Number(v).toFixed(3)} /><ReferenceLine y={0} stroke="#666" strokeOpacity={0.3} /><ReferenceLine y={0.5} stroke="#10b981" strokeDasharray="2 2" strokeOpacity={0.3} /><ReferenceLine y={-0.5} stroke="#ef4444" strokeDasharray="2 2" strokeOpacity={0.3} /><Line type="monotone" dataKey="corr" stroke="#3b82f6" strokeWidth={2} dot={false} /></LineChart></ResponsiveContainer></div></CardContent></Card>
        <Card><CardHeader className="py-2"><CardTitle className="text-xs">Z-Score (Deviation from Historical Mean)</CardTitle></CardHeader><CardContent><div className="h-[150px]"><ResponsiveContainer width="100%" height="100%"><LineChart data={rollingCorr.map(r => ({ time: fmtTime(r.time), zScore: r.zScore }))}><CartesianGrid strokeDasharray="3 3" stroke="hsl(var(--border))" opacity={0.2} /><XAxis dataKey="time" tick={{ fontSize: 9, fill: "hsl(var(--muted-foreground))" }} interval={Math.max(1, Math.floor(rollingCorr.length / 8))} /><YAxis tick={{ fontSize: 10, fill: "hsl(var(--muted-foreground))" }} width={40} /><Tooltip formatter={(v: any) => Number(v).toFixed(2)} /><ReferenceLine y={0} stroke="#666" strokeOpacity={0.3} /><ReferenceLine y={2} stroke="#ef4444" strokeDasharray="3 3" strokeOpacity={0.4} /><ReferenceLine y={-2} stroke="#ef4444" strokeDasharray="3 3" strokeOpacity={0.4} /><Line type="monotone" dataKey="zScore" stroke="#f59e0b" strokeWidth={1.5} dot={false} /></LineChart></ResponsiveContainer></div></CardContent></Card>
      </div>)}
    </div>
  );
}
