"use client";
import { useMemo, useState } from "react";
import { useTradingStore } from "@/lib/trading/store";
import { CONTRACTS } from "@/lib/trading/contracts";
import { computeMonthlySeasonality, computeAllSeasonality, getActiveSeasonalWindows, getUpcomingCalendarEvents, SEASONAL_WINDOWS, computeDayOfWeekStats } from "@/lib/trading/seasonality";
import { fmtPct } from "@/lib/trading/format";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Bar, BarChart, CartesianGrid, Cell, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { cn } from "@/lib/utils";
import { Calendar, Flame } from "lucide-react";

type View = "monthly" | "windows" | "ranking" | "calendar";
const VIEWS: { id: View; name: string }[] = [{ id: "monthly", name: "Monthly Patterns" }, { id: "windows", name: "Seasonal Windows" }, { id: "ranking", name: "All Symbols Ranking" }, { id: "calendar", name: "Calendar Events" }];

export function SeasonalityAnalyzer() {
  const [view, setView] = useState<View>("monthly");
  const [symbol, setSymbol] = useState("ES");
  const selectSymbol = useTradingStore((s) => s.selectSymbol);
  const tickCount = useTradingStore((s) => s.tickCount);
  const seasonality = useMemo(() => computeMonthlySeasonality(symbol), [symbol, tickCount]);
  const rankings = useMemo(() => computeAllSeasonality(), [tickCount]);
  const activeWindows = useMemo(() => getActiveSeasonalWindows(symbol), [symbol]);
  const calendarEvents = useMemo(() => getUpcomingCalendarEvents(), []);

  return (
    <div className="space-y-4">
      <div className="flex items-center gap-1 flex-wrap">{VIEWS.map(v => <button key={v.id} onClick={() => setView(v.id)} className={cn("px-3 py-1.5 rounded-md text-xs border transition-colors", view === v.id ? "bg-primary/15 text-primary border-primary/30" : "border-border text-muted-foreground hover:bg-muted/40")}>{v.name}</button>)}</div>
      {view === "monthly" && seasonality && (
        <div className="space-y-3">
          <Card><CardContent className="p-3 flex items-center gap-3"><select value={symbol} onChange={(e) => { setSymbol(e.target.value); selectSymbol(e.target.value); }} className="bg-muted/50 border border-border rounded px-2 py-1.5 text-xs font-mono">{CONTRACTS.map(c => <option key={c.symbol} value={c.symbol}>{c.symbol} · {c.name}</option>)}</select>
            <div className="flex items-center gap-4 text-xs"><span>Best: <span className="text-emerald-400 font-mono font-semibold">{seasonality.bestMonth.monthName} ({fmtPct(seasonality.bestMonth.avgReturn)})</span></span><span>Worst: <span className="text-rose-400 font-mono font-semibold">{seasonality.worstMonth.monthName} ({fmtPct(seasonality.worstMonth.avgReturn)})</span></span><span>Sell in May: <span className={cn("font-mono font-semibold", seasonality.sellInMay > 0 ? "text-emerald-400" : "text-rose-400")}>{fmtPct(seasonality.sellInMay)}</span></span></div>
          </CardContent></Card>
          <Card><CardHeader className="py-2"><CardTitle className="text-xs">{seasonality.name} — Average Monthly Returns (%)</CardTitle></CardHeader><CardContent><div className="h-[300px]"><ResponsiveContainer width="100%" height="100%"><BarChart data={seasonality.monthlyStats.map(m => ({ month: m.monthName, avg: m.avgReturn, sig: m.isSignificant }))}><CartesianGrid strokeDasharray="3 3" stroke="hsl(var(--border))" opacity={0.2} /><XAxis dataKey="month" tick={{ fontSize: 11, fill: "hsl(var(--muted-foreground))" }} /><YAxis tick={{ fontSize: 10, fill: "hsl(var(--muted-foreground))" }} width={50} tickFormatter={v => `${v.toFixed(1)}%`} /><Tooltip formatter={(v: any) => `${Number(v).toFixed(2)}%`} /><ReferenceLine y={0} stroke="#666" /><Bar dataKey="avg" radius={[2,2,0,0]}>{seasonality.monthlyStats.map((m,i) => <Cell key={i} fill={m.avgReturn >= 0 ? (m.isSignificant ? "#10b981" : "#10b98188") : (m.isSignificant ? "#ef4444" : "#ef444488")} />)}</Bar></BarChart></ResponsiveContainer></div></CardContent></Card>
          <Card><CardHeader className="py-2"><CardTitle className="text-xs">Monthly Statistics</CardTitle></CardHeader><CardContent className="p-0"><div className="overflow-x-auto"><table className="w-full text-xs"><thead className="bg-muted/40 border-y border-border"><tr className="text-muted-foreground text-[10px] uppercase"><th className="text-left py-2 px-3">Month</th><th className="text-right py-2 px-3">Avg</th><th className="text-right py-2 px-3">Hit Rate</th><th className="text-right py-2 px-3">Std Dev</th><th className="text-right py-2 px-3">t-Stat</th><th className="text-center py-2 px-3">Sig?</th></tr></thead><tbody>{seasonality.monthlyStats.map(m => <tr key={m.month} className="border-b border-border/40"><td className="py-1.5 px-3 font-medium">{m.monthName}</td><td className={cn("py-1.5 px-3 text-right font-mono", m.avgReturn >= 0 ? "text-emerald-400" : "text-rose-400")}>{fmtPct(m.avgReturn)}</td><td className="py-1.5 px-3 text-right font-mono">{(m.positiveRate * 100).toFixed(0)}%</td><td className="py-1.5 px-3 text-right font-mono text-muted-foreground">{m.stdDev.toFixed(2)}</td><td className={cn("py-1.5 px-3 text-right font-mono", Math.abs(m.tStat) > 2 ? "text-amber-400 font-semibold" : "")}>{m.tStat.toFixed(2)}</td><td className="py-1.5 px-3 text-center">{m.isSignificant ? <Badge variant="outline" className="text-[9px] bg-amber-500/15 text-amber-400">YES</Badge> : <span className="text-[10px] text-muted-foreground">—</span>}</td></tr>)}</tbody></table></div></CardContent></Card>
        </div>
      )}
      {view === "windows" && (
        <div className="space-y-3">
          {activeWindows.length > 0 && <Card className="border-amber-500/30 bg-amber-500/5"><CardHeader className="py-2"><CardTitle className="text-xs flex items-center gap-2"><Flame className="w-3.5 h-3.5 text-amber-400" /> Active Windows for {symbol}</CardTitle></CardHeader><CardContent className="space-y-2">{activeWindows.map((w, i) => <div key={i} className="border border-border/40 rounded-md p-2.5"><div className="flex items-center justify-between mb-1"><span className="text-xs font-semibold">{w.name}</span><Badge variant="outline" className={cn("text-[9px]", w.direction === "LONG" ? "bg-emerald-500/15 text-emerald-400" : "bg-rose-500/15 text-rose-400")}>{w.direction}</Badge></div><p className="text-[10px] text-muted-foreground">{w.description}</p><div className="flex items-center gap-3 mt-1 text-[10px] font-mono"><span>Avg: <span className={cn("font-semibold", w.avgReturn >= 0 ? "text-emerald-400" : "text-rose-400")}>{fmtPct(w.avgReturn)}</span></span><span>Hit Rate: <span className="font-semibold">{(w.hitRate * 100).toFixed(0)}%</span></span></div></div>)}</CardContent></Card>}
          <Card><CardHeader className="py-2"><CardTitle className="text-xs">All Seasonal Windows ({SEASONAL_WINDOWS.length})</CardTitle></CardHeader><CardContent className="space-y-2 pt-0">{SEASONAL_WINDOWS.map((w, i) => <div key={i} className={cn("border rounded-md p-2.5", w.symbol === symbol ? "border-primary/30 bg-primary/5" : "border-border/40 bg-muted/20")}><div className="flex items-center justify-between mb-1"><div className="flex items-center gap-2"><Badge variant="outline" className="text-[9px] font-mono">{w.symbol}</Badge><span className="text-xs font-semibold">{w.name}</span></div><div className="flex items-center gap-1">{w.significance === "HIGH" && <Badge variant="outline" className="text-[9px] bg-emerald-500/15 text-emerald-400">HIGH</Badge>}<Badge variant="outline" className={cn("text-[9px]", w.direction === "LONG" ? "bg-emerald-500/15 text-emerald-400" : "bg-rose-500/15 text-rose-400")}>{w.direction}</Badge></div></div><p className="text-[10px] text-muted-foreground">{w.description}</p><div className="flex items-center gap-3 mt-1 text-[10px] font-mono"><span>Avg: <span className={cn("font-semibold", w.avgReturn >= 0 ? "text-emerald-400" : "text-rose-400")}>{fmtPct(w.avgReturn)}</span></span><span>Hit: <span className="font-semibold">{(w.hitRate * 100).toFixed(0)}%</span></span></div></div>)}</CardContent></Card>
        </div>
      )}
      {view === "ranking" && <Card><CardHeader className="py-2"><CardTitle className="text-xs">Seasonality Strength Ranking</CardTitle></CardHeader><CardContent className="p-0"><div className="overflow-x-auto"><table className="w-full text-xs"><thead className="bg-muted/40 border-y border-border"><tr className="text-muted-foreground text-[10px] uppercase"><th className="text-left py-2 px-3">#</th><th className="text-left py-2 px-3">Symbol</th><th className="text-right py-2 px-3">Strength</th><th className="text-right py-2 px-3">Best Month</th><th className="text-right py-2 px-3">Worst Month</th><th className="text-right py-2 px-3">Sell in May</th><th className="text-center py-2 px-3">Current Rank</th></tr></thead><tbody>{rankings.map((r, i) => <tr key={r.symbol} className="border-b border-border/40 hover:bg-muted/30 cursor-pointer" onClick={() => { setSymbol(r.symbol); selectSymbol(r.symbol); setView("monthly"); }}><td className="py-1.5 px-3 font-mono text-[10px] text-muted-foreground">{i+1}</td><td className="py-1.5 px-3 font-mono font-medium">{r.symbol}</td><td className="py-1.5 px-3 text-right"><div className="flex items-center justify-end gap-1.5"><div className="w-12 h-1.5 bg-muted rounded-full overflow-hidden"><div className={cn("h-full", r.strength > 0.5 ? "bg-emerald-500" : r.strength > 0.25 ? "bg-amber-500" : "bg-muted-foreground")} style={{ width: `${r.strength * 100}%` }} /></div><span className="font-mono text-[10px] w-8">{(r.strength * 100).toFixed(0)}%</span></div></td><td className="py-1.5 px-3 text-right font-mono text-emerald-400">{r.bestMonth} ({fmtPct(r.bestMonthReturn)})</td><td className="py-1.5 px-3 text-right font-mono text-rose-400">{r.worstMonth} ({fmtPct(r.worstMonthReturn)})</td><td className={cn("py-1.5 px-3 text-right font-mono", r.sellInMay > 0 ? "text-emerald-400" : "text-rose-400")}>{fmtPct(r.sellInMay)}</td><td className="py-1.5 px-3 text-center"><Badge variant="outline" className="text-[9px]">{r.currentMonthRank}/12</Badge></td></tr>)}</tbody></table></div></CardContent></Card>}
      {view === "calendar" && <Card><CardHeader className="py-2"><CardTitle className="text-xs flex items-center gap-2"><Calendar className="w-3.5 h-3.5" /> Upcoming Calendar Events</CardTitle></CardHeader><CardContent className="space-y-2 pt-0">{calendarEvents.map((e, i) => <div key={i} className={cn("border rounded-md p-2.5", e.daysAway <= 3 ? "border-amber-500/30 bg-amber-500/5" : "border-border/40 bg-muted/20")}><div className="flex items-center justify-between"><div className="flex items-center gap-2"><span className="text-xs font-mono text-muted-foreground">{e.date}</span><Badge variant="outline" className={cn("text-[9px]", e.type === "FOMC" ? "bg-rose-500/15 text-rose-400" : e.type === "NFP" ? "bg-amber-500/15 text-amber-400" : "bg-blue-500/15 text-blue-400")}>{e.type}</Badge><span className="text-xs font-semibold">{e.name}</span></div><span className="text-[10px] font-mono text-muted-foreground">{e.daysAway}d away</span></div><p className="text-[10px] text-muted-foreground mt-1">{e.description}</p><div className="flex items-center gap-1 mt-1.5"><span className="text-[9px] text-muted-foreground">Affected:</span>{e.affectedSymbols.map(s => <Badge key={s} variant="outline" className="text-[9px] h-4 px-1 font-mono">{s}</Badge>)}</div></div>)}</CardContent></Card>}
    </div>
  );
}
