/**
 * Alerts & Watchlist Engine
 *
 * Three alert families:
 *  - PRICE: cross above/below threshold, % change from anchor
 *  - TECHNICAL: RSI overbought/oversold, SMA cross, BB band touch, ATR spike
 *  - STRATEGY: signal generated by any active strategy
 *
 * Watchlists are user-defined symbol groups with optional notes and target prices.
 */
import type { Candle, Quote } from "./types";
import { atr, bollingerBands, rsi, sma } from "./indicators";

export type AlertCondition =
  | "PRICE_ABOVE"
  | "PRICE_BELOW"
  | "PCT_CHANGE_UP"
  | "PCT_CHANGE_DOWN"
  | "RSI_OVERBOUGHT"
  | "RSI_OVERSOLD"
  | "SMA_CROSS_UP"
  | "SMA_CROSS_DOWN"
  | "BB_UPPER_TOUCH"
  | "BB_LOWER_TOUCH"
  | "ATR_SPIKE"
  | "VOLUME_SPIKE";

export interface PriceAlert {
  id: string;
  symbol: string;
  condition: AlertCondition;
  threshold: number; // depends on condition (price level, % chg, RSI level, etc.)
  name: string;
  enabled: boolean;
  triggered: boolean;
  triggeredAt?: number;
  triggeredValue?: number;
  createdAt: number;
  // For change-from-anchor alerts, we capture the price at creation
  anchorPrice?: number;
  // For SMA cross, we track last state
  lastState?: "ABOVE" | "BELOW";
}

let alertCounter = 0;
export function makeAlertId(): string {
  return `pa-${Date.now().toString(36)}-${alertCounter++}`;
}

export function createPriceAlert(
  symbol: string,
  condition: AlertCondition,
  threshold: number,
  name: string,
  anchorPrice?: number,
): PriceAlert {
  return {
    id: makeAlertId(),
    symbol,
    condition,
    threshold,
    name,
    enabled: true,
    triggered: false,
    createdAt: Date.now(),
    anchorPrice,
  };
}

/**
 * Evaluate a price alert against current quote + candle history.
 * Returns true if the alert just transitioned to triggered state.
 */
export function evaluateAlert(alert: PriceAlert, quote: Quote, candles: Candle[]): boolean {
  if (!alert.enabled || alert.triggered) return false;
  const price = quote.last;
  let shouldFire = false;
  switch (alert.condition) {
    case "PRICE_ABOVE":
      shouldFire = price >= alert.threshold;
      break;
    case "PRICE_BELOW":
      shouldFire = price <= alert.threshold;
      break;
    case "PCT_CHANGE_UP":
      if (alert.anchorPrice) {
        const pct = (price - alert.anchorPrice) / alert.anchorPrice;
        shouldFire = pct * 100 >= alert.threshold;
      }
      break;
    case "PCT_CHANGE_DOWN":
      if (alert.anchorPrice) {
        const pct = (price - alert.anchorPrice) / alert.anchorPrice;
        shouldFire = pct * 100 <= -alert.threshold;
      }
      break;
    case "RSI_OVERBOUGHT": {
      const rsiArr = rsi(candles.map((c) => c.close), 14);
      const last = rsiArr[rsiArr.length - 1];
      if (last != null) shouldFire = last >= alert.threshold;
      break;
    }
    case "RSI_OVERSOLD": {
      const rsiArr = rsi(candles.map((c) => c.close), 14);
      const last = rsiArr[rsiArr.length - 1];
      if (last != null) shouldFire = last <= alert.threshold;
      break;
    }
    case "SMA_CROSS_UP": {
      const smaArr = sma(candles.map((c) => c.close), Math.round(alert.threshold));
      const lastSma = smaArr[smaArr.length - 1];
      const prevSma = smaArr[smaArr.length - 2];
      if (lastSma != null && prevSma != null) {
        const currentState: "ABOVE" | "BELOW" = price >= (lastSma as number) ? "ABOVE" : "BELOW";
        if (alert.lastState === "BELOW" && currentState === "ABOVE") {
          shouldFire = true;
        }
        alert.lastState = currentState;
      }
      break;
    }
    case "SMA_CROSS_DOWN": {
      const smaArr = sma(candles.map((c) => c.close), Math.round(alert.threshold));
      const lastSma = smaArr[smaArr.length - 1];
      if (lastSma != null) {
        const currentState: "ABOVE" | "BELOW" = price >= (lastSma as number) ? "ABOVE" : "BELOW";
        if (alert.lastState === "ABOVE" && currentState === "BELOW") {
          shouldFire = true;
        }
        alert.lastState = currentState;
      }
      break;
    }
    case "BB_UPPER_TOUCH": {
      const bb = bollingerBands(candles.map((c) => c.close), 20, 2);
      const upper = bb.upper[bb.upper.length - 1];
      if (upper != null) shouldFire = price >= (upper as number);
      break;
    }
    case "BB_LOWER_TOUCH": {
      const bb = bollingerBands(candles.map((c) => c.close), 20, 2);
      const lower = bb.lower[bb.lower.length - 1];
      if (lower != null) shouldFire = price <= (lower as number);
      break;
    }
    case "ATR_SPIKE": {
      const atrArr = atr(candles, 14);
      const lastAtr = atrArr[atrArr.length - 1];
      const prevAtr = atrArr[atrArr.length - 2];
      if (lastAtr != null && prevAtr != null) {
        shouldFire = (lastAtr as number) > (prevAtr as number) * (1 + alert.threshold / 100);
      }
      break;
    }
    case "VOLUME_SPIKE": {
      // Use last 20 candles as baseline
      if (candles.length < 25) break;
      const baseline = candles.slice(-25, -5).reduce((s, c) => s + c.volume, 0) / 20;
      const recent = candles[candles.length - 1].volume;
      shouldFire = recent > baseline * (1 + alert.threshold / 100);
      break;
    }
  }
  if (shouldFire) {
    alert.triggered = true;
    alert.triggeredAt = Date.now();
    alert.triggeredValue = price;
  }
  return shouldFire;
}

// ============================================================
// Watchlists
// ============================================================

export interface WatchlistEntry {
  symbol: string;
  note?: string;
  targetPrice?: number;
  stopPrice?: number;
  addedAt: number;
}

export interface Watchlist {
  id: string;
  name: string;
  entries: WatchlistEntry[];
  createdAt: number;
}

let wlCounter = 0;
export function makeWatchlistId(): string {
  return `wl-${Date.now().toString(36)}-${wlCounter++}`;
}

export const DEFAULT_WATCHLISTS: Watchlist[] = [
  {
    id: makeWatchlistId(),
    name: "Index Futures",
    createdAt: Date.now(),
    entries: [
      { symbol: "ES", note: "S&P 500 — primary", addedAt: Date.now() },
      { symbol: "NQ", note: "Nasdaq-100 — momentum", addedAt: Date.now() },
      { symbol: "MNQ", note: "Micro Nasdaq — small size", addedAt: Date.now() },
      { symbol: "RTY", addedAt: Date.now() },
      { symbol: "YM", addedAt: Date.now() },
    ],
  },
  {
    id: makeWatchlistId(),
    name: "Rates & Macro",
    createdAt: Date.now(),
    entries: [
      { symbol: "ZN", note: "10Y — duration play", addedAt: Date.now() },
      { symbol: "ZB", addedAt: Date.now() },
      { symbol: "SR3", note: "SOFR — Fed policy proxy", addedAt: Date.now() },
    ],
  },
  {
    id: makeWatchlistId(),
    name: "Commodities",
    createdAt: Date.now(),
    entries: [
      { symbol: "CL", note: "WTI — watch OPEC", addedAt: Date.now() },
      { symbol: "GC", note: "Gold — inflation hedge", addedAt: Date.now() },
      { symbol: "SI", addedAt: Date.now() },
      { symbol: "NG", addedAt: Date.now() },
    ],
  },
  {
    id: makeWatchlistId(),
    name: "Micros (small account)",
    createdAt: Date.now(),
    entries: [
      { symbol: "MNQ", note: "1/10 NQ — lowest margin", addedAt: Date.now() },
      { symbol: "MES", addedAt: Date.now() },
      { symbol: "M2K", addedAt: Date.now() },
      { symbol: "MYM", addedAt: Date.now() },
      { symbol: "MCL", addedAt: Date.now() },
      { symbol: "MGC", addedAt: Date.now() },
    ],
  },
];
