/**
 * Futures Contract Universe
 * Real CME / ICE / EUREX specifications that TwigCapra is known to trade.
 * Margins approximate current exchange maintenance levels (illustrative).
 */
import type { FuturesContract } from "./types";

export const CONTRACTS: FuturesContract[] = [
  // ===== Equity Index Futures (CME) =====
  {
    symbol: "ES",
    name: "E-mini S&P 500",
    exchange: "CME",
    assetClass: "equity_index",
    tickSize: 0.25,
    tickValue: 12.5,
    contractSize: 50,
    multiplier: 50,
    pointValue: 50,
    marginInitial: 13200,
    marginMaintenance: 12000,
    months: ["H", "M", "U", "Z"],
    settlement: "cash",
    currency: "USD",
    basePrice: 5480.25,
    volatility: 0.16,
    drift: 0.08,
    session: "RTH",
  },
  {
    symbol: "NQ",
    name: "E-mini Nasdaq-100",
    exchange: "CME",
    assetClass: "equity_index",
    tickSize: 0.25,
    tickValue: 5,
    contractSize: 20,
    multiplier: 20,
    pointValue: 20,
    marginInitial: 16500,
    marginMaintenance: 15000,
    months: ["H", "M", "U", "Z"],
    settlement: "cash",
    currency: "USD",
    basePrice: 19250.5,
    volatility: 0.22,
    drift: 0.10,
    session: "RTH",
  },
  {
    symbol: "RTY",
    name: "E-mini Russell 2000",
    exchange: "CME",
    assetClass: "equity_index",
    tickSize: 0.1,
    tickValue: 10,
    contractSize: 100,
    multiplier: 100,
    pointValue: 100,
    marginInitial: 9900,
    marginMaintenance: 9000,
    months: ["H", "M", "U", "Z"],
    settlement: "cash",
    currency: "USD",
    basePrice: 2185.4,
    volatility: 0.20,
    drift: 0.07,
    session: "RTH",
  },
  {
    symbol: "YM",
    name: "E-mini Dow",
    exchange: "CBOT",
    assetClass: "equity_index",
    tickSize: 1,
    tickValue: 5,
    contractSize: 5,
    multiplier: 5,
    pointValue: 5,
    marginInitial: 11000,
    marginMaintenance: 10000,
    months: ["H", "M", "U", "Z"],
    settlement: "cash",
    currency: "USD",
    basePrice: 42580,
    volatility: 0.15,
    drift: 0.07,
    session: "RTH",
  },
  // ===== Interest Rate Futures =====
  {
    symbol: "ZN",
    name: "10-Year T-Note",
    exchange: "CBOT",
    assetClass: "rate",
    tickSize: 0.015625, // 1/64
    tickValue: 31.25,
    contractSize: 100000,
    multiplier: 1000,
    pointValue: 1000,
    marginInitial: 1450,
    marginMaintenance: 1320,
    months: ["H", "M", "U", "Z"],
    settlement: "physical",
    currency: "USD",
    basePrice: 109.265625,
    volatility: 0.06,
    drift: -0.02,
    session: "GLO",
  },
  {
    symbol: "ZB",
    name: "30-Year T-Bond",
    exchange: "CBOT",
    assetClass: "rate",
    tickSize: 0.03125, // 1/32
    tickValue: 31.25,
    contractSize: 100000,
    multiplier: 1000,
    pointValue: 1000,
    marginInitial: 2750,
    marginMaintenance: 2500,
    months: ["H", "M", "U", "Z"],
    settlement: "physical",
    currency: "USD",
    basePrice: 117.15625,
    volatility: 0.10,
    drift: -0.03,
    session: "GLO",
  },
  {
    symbol: "SR3",
    name: "SOFR 3M",
    exchange: "CME",
    assetClass: "rate",
    tickSize: 0.0025, // 1/4 bp
    tickValue: 25,
    contractSize: 2500,
    multiplier: 2500,
    pointValue: 2500,
    marginInitial: 950,
    marginMaintenance: 850,
    months: ["H", "M", "U", "Z"],
    settlement: "cash",
    currency: "USD",
    basePrice: 95.4525,
    volatility: 0.04,
    drift: -0.01,
    session: "GLO",
  },
  // ===== Energy =====
  {
    symbol: "CL",
    name: "WTI Crude Oil",
    exchange: "NYMEX",
    assetClass: "energy",
    tickSize: 0.01,
    tickValue: 10,
    contractSize: 1000,
    multiplier: 1000,
    pointValue: 1000,
    marginInitial: 7150,
    marginMaintenance: 6500,
    months: ["F", "G", "H", "J", "K", "M", "N", "Q", "U", "V", "X", "Z"],
    settlement: "physical",
    currency: "USD",
    basePrice: 81.42,
    volatility: 0.32,
    drift: 0.0,
    session: "GLO",
  },
  {
    symbol: "NG",
    name: "Henry Hub Natural Gas",
    exchange: "NYMEX",
    assetClass: "energy",
    tickSize: 0.001,
    tickValue: 10,
    contractSize: 10000,
    multiplier: 10000,
    pointValue: 10000,
    marginInitial: 4950,
    marginMaintenance: 4500,
    months: ["F", "G", "H", "J", "K", "M", "N", "Q", "U", "V", "X", "Z"],
    settlement: "physical",
    currency: "USD",
    basePrice: 2.345,
    volatility: 0.55,
    drift: -0.05,
    session: "GLO",
  },
  // ===== Metals =====
  {
    symbol: "GC",
    name: "Gold",
    exchange: "COMEX",
    assetClass: "metal",
    tickSize: 0.1,
    tickValue: 10,
    contractSize: 100,
    multiplier: 100,
    pointValue: 100,
    marginInitial: 9900,
    marginMaintenance: 9000,
    months: ["G", "J", "M", "Q", "Z"],
    settlement: "physical",
    currency: "USD",
    basePrice: 2385.6,
    volatility: 0.14,
    drift: 0.06,
    session: "GLO",
  },
  {
    symbol: "SI",
    name: "Silver",
    exchange: "COMEX",
    assetClass: "metal",
    tickSize: 0.005,
    tickValue: 25,
    contractSize: 5000,
    multiplier: 5000,
    pointValue: 5000,
    marginInitial: 11000,
    marginMaintenance: 10000,
    months: ["F", "H", "K", "N", "U", "Z"],
    settlement: "physical",
    currency: "USD",
    basePrice: 30.875,
    volatility: 0.26,
    drift: 0.05,
    session: "GLO",
  },
  // ===== FX Futures =====
  {
    symbol: "6E",
    name: "Euro FX",
    exchange: "CME",
    assetClass: "fx",
    tickSize: 0.00005,
    tickValue: 6.25,
    contractSize: 125000,
    multiplier: 125000,
    pointValue: 125000,
    marginInitial: 2750,
    marginMaintenance: 2500,
    months: ["H", "M", "U", "Z"],
    settlement: "physical",
    currency: "USD",
    basePrice: 1.0842,
    volatility: 0.08,
    drift: -0.01,
    session: "GLO",
  },
  {
    symbol: "6B",
    name: "British Pound",
    exchange: "CME",
    assetClass: "fx",
    tickSize: 0.0001,
    tickValue: 6.25,
    contractSize: 62500,
    multiplier: 62500,
    pointValue: 62500,
    marginInitial: 2420,
    marginMaintenance: 2200,
    months: ["H", "M", "U", "Z"],
    settlement: "physical",
    currency: "USD",
    basePrice: 1.2785,
    volatility: 0.09,
    drift: 0.0,
    session: "GLO",
  },
  // ===== Crypto =====
  {
    symbol: "BRR",
    name: "Bitcoin (CME)",
    exchange: "CME",
    assetClass: "crypto",
    tickSize: 5,
    tickValue: 25,
    contractSize: 5,
    multiplier: 5,
    pointValue: 5,
    marginInitial: 44000,
    marginMaintenance: 40000,
    months: ["F", "G", "H", "J", "K", "M", "N", "Q", "U", "V", "X", "Z"],
    settlement: "cash",
    currency: "USD",
    basePrice: 62850,
    volatility: 0.65,
    drift: 0.20,
    session: "GLO",
  },
  // ===== Micro E-mini Futures (CME Micros — 1/10th size of E-minis) =====
  {
    symbol: "MNQ",
    name: "Micro E-mini Nasdaq-100",
    exchange: "CME",
    assetClass: "equity_index",
    tickSize: 0.25,
    tickValue: 0.5,
    contractSize: 2,
    multiplier: 2,
    pointValue: 2,
    marginInitial: 1650,
    marginMaintenance: 1500,
    months: ["H", "M", "U", "Z"],
    settlement: "cash",
    currency: "USD",
    basePrice: 19250.5,
    volatility: 0.22,
    drift: 0.10,
    session: "RTH",
  },
  {
    symbol: "MES",
    name: "Micro E-mini S&P 500",
    exchange: "CME",
    assetClass: "equity_index",
    tickSize: 0.25,
    tickValue: 1.25,
    contractSize: 5,
    multiplier: 5,
    pointValue: 5,
    marginInitial: 1320,
    marginMaintenance: 1200,
    months: ["H", "M", "U", "Z"],
    settlement: "cash",
    currency: "USD",
    basePrice: 5480.25,
    volatility: 0.16,
    drift: 0.08,
    session: "RTH",
  },
  {
    symbol: "M2K",
    name: "Micro E-mini Russell 2000",
    exchange: "CME",
    assetClass: "equity_index",
    tickSize: 0.1,
    tickValue: 1,
    contractSize: 10,
    multiplier: 10,
    pointValue: 10,
    marginInitial: 990,
    marginMaintenance: 900,
    months: ["H", "M", "U", "Z"],
    settlement: "cash",
    currency: "USD",
    basePrice: 2185.4,
    volatility: 0.20,
    drift: 0.07,
    session: "RTH",
  },
  {
    symbol: "MYM",
    name: "Micro E-mini Dow",
    exchange: "CBOT",
    assetClass: "equity_index",
    tickSize: 1,
    tickValue: 0.5,
    contractSize: 0.5,
    multiplier: 0.5,
    pointValue: 0.5,
    marginInitial: 1100,
    marginMaintenance: 1000,
    months: ["H", "M", "U", "Z"],
    settlement: "cash",
    currency: "USD",
    basePrice: 42580,
    volatility: 0.15,
    drift: 0.07,
    session: "RTH",
  },
  // ===== Micro Energy / Metals =====
  {
    symbol: "MCL",
    name: "Micro WTI Crude Oil",
    exchange: "NYMEX",
    assetClass: "energy",
    tickSize: 0.01,
    tickValue: 1,
    contractSize: 100,
    multiplier: 100,
    pointValue: 100,
    marginInitial: 715,
    marginMaintenance: 650,
    months: ["F", "G", "H", "J", "K", "M", "N", "Q", "U", "V", "X", "Z"],
    settlement: "physical",
    currency: "USD",
    basePrice: 81.42,
    volatility: 0.32,
    drift: 0.0,
    session: "GLO",
  },
  {
    symbol: "MGC",
    name: "Micro Gold",
    exchange: "COMEX",
    assetClass: "metal",
    tickSize: 0.1,
    tickValue: 1,
    contractSize: 10,
    multiplier: 10,
    pointValue: 10,
    marginInitial: 990,
    marginMaintenance: 900,
    months: ["G", "J", "M", "Q", "Z"],
    settlement: "physical",
    currency: "USD",
    basePrice: 2385.6,
    volatility: 0.14,
    drift: 0.06,
    session: "GLO",
  },
  {
    symbol: "SIL",
    name: "Micro Silver",
    exchange: "COMEX",
    assetClass: "metal",
    tickSize: 0.005,
    tickValue: 2.5,
    contractSize: 500,
    multiplier: 500,
    pointValue: 500,
    marginInitial: 1100,
    marginMaintenance: 1000,
    months: ["F", "H", "K", "N", "U", "Z"],
    settlement: "physical",
    currency: "USD",
    basePrice: 30.875,
    volatility: 0.26,
    drift: 0.05,
    session: "GLO",
  },
  // ===== Micro FX =====
  {
    symbol: "M6E",
    name: "Micro Euro FX",
    exchange: "CME",
    assetClass: "fx",
    tickSize: 0.00005,
    tickValue: 0.625,
    contractSize: 12500,
    multiplier: 12500,
    pointValue: 12500,
    marginInitial: 275,
    marginMaintenance: 250,
    months: ["H", "M", "U", "Z"],
    settlement: "physical",
    currency: "USD",
    basePrice: 1.0842,
    volatility: 0.08,
    drift: -0.01,
    session: "GLO",
  },
  // ===== Micro Treasury =====
  {
    symbol: "MUB",
    name: "Micro 10-Year Yield",
    exchange: "CBOT",
    assetClass: "rate",
    tickSize: 0.005,
    tickValue: 5,
    contractSize: 1000,
    multiplier: 1000,
    pointValue: 1000,
    marginInitial: 145,
    marginMaintenance: 130,
    months: ["H", "M", "U", "Z"],
    settlement: "cash",
    currency: "USD",
    basePrice: 109.265625,
    volatility: 0.06,
    drift: -0.02,
    session: "GLO",
  },
];

export const CONTRACT_MAP: Record<string, FuturesContract> = CONTRACTS.reduce(
  (acc, c) => {
    acc[c.symbol] = c;
    return acc;
  },
  {} as Record<string, FuturesContract>,
);

export function getContract(symbol: string): FuturesContract {
  const c = CONTRACT_MAP[symbol];
  if (!c) throw new Error(`Unknown contract: ${symbol}`);
  return c;
}

/** Beta relative to ES (proxy for SPX) — used for portfolio risk. */
export const BETAS: Record<string, number> = {
  ES: 1.0,
  NQ: 1.15,
  RTY: 1.2,
  YM: 0.95,
  ZN: -0.1,
  ZB: -0.15,
  SR3: -0.05,
  CL: 0.4,
  NG: 0.2,
  GC: 0.1,
  SI: 0.3,
  "6E": -0.2,
  "6B": -0.15,
  BRR: 1.8,
  // Micros (mirror their full-size equivalents)
  MES: 1.0,
  MNQ: 1.15,
  M2K: 1.2,
  MYM: 0.95,
  MCL: 0.4,
  MGC: 0.1,
  SIL: 0.3,
  M6E: -0.2,
  MUB: -0.1,
};

/** Mapping of micro contracts to their full-size equivalents (for spread trading & margin offsets). */
export const MICRO_TO_FULL: Record<string, string> = {
  MES: "ES",
  MNQ: "NQ",
  M2K: "RTY",
  MYM: "YM",
  MCL: "CL",
  MGC: "GC",
  SIL: "SI",
  M6E: "6E",
  MUB: "ZN",
};

/** Ratio of micro size to full size (e.g., MNQ is 1/10 of NQ). */
export const MICRO_RATIOS: Record<string, number> = {
  MES: 1 / 10,
  MNQ: 1 / 10,
  M2K: 1 / 10,
  MYM: 1 / 10,
  MCL: 1 / 10,
  MGC: 1 / 10,
  SIL: 1 / 10,
  M6E: 1 / 10,
  MUB: 1 / 100,
};
